# Generated by Django 3.2.8 on 2021-10-19 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matches',
            old_name='left_company_id',
            new_name='left_company',
        ),
        migrations.RenameField(
            model_name='matches',
            old_name='right_company_id',
            new_name='right_company',
        ),
    ]
